/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllowIPsManager: typeof import('./src/components/AllowIPsManager.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    InSideLayout: typeof import('./src/components/layout/InSideLayout.vue')['default']
    MainMenu: typeof import('./src/components/global/MainMenu.vue')['default']
    MemberLayout: typeof import('./src/components/layout/MemberLayout.vue')['default']
    OutSideLayout: typeof import('./src/components/layout/OutSideLayout.vue')['default']
    PageTitle: typeof import('./src/components/global/PageTitle.vue')['default']
    Pagination: typeof import('./src/components/global/Pagination.vue')['default']
    PortalLayout: typeof import('./src/components/layout/PortalLayout.vue')['default']
    PortalNavigation: typeof import('./src/components/layout/PortalNavigation.vue')['default']
    QuillEditor: typeof import('./src/components/QuillEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResultLayout: typeof import('./src/components/layout/SearchResultLayout.vue')['default']
    SelectMemberStatus: typeof import('./src/components/select/SelectMemberStatus.vue')['default']
    SelectOrderStatus: typeof import('./src/components/select/SelectOrderStatus.vue')['default']
    SelectProductCategory: typeof import('./src/components/select/SelectProductCategory.vue')['default']
    SelectStatus: typeof import('./src/components/select/SelectStatus.vue')['default']
    SelectUnit: typeof import('./src/components/select/SelectUnit.vue')['default']
    SubTitle: typeof import('./src/components/global/SubTitle.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
